config/routes.rb
Rails.application.routes.draw do
  root 'common_pages#index'

  get '/locale/:locale', to: 'service#locale', as: :set_locale

  namespace :admin do
    resources :lifetimes
    resources :passkeys
    resources :periods
    resources :subscriptions
    resources :users

    root to: 'users#index'
  end

  # namespace :api do
  # 	get '/lifetimes/', to: 'lifetimes#index'
  # 	get '/lifetimes/:id/', to: 'lifetimes#single'
  # 	patch '/lifetimes/:id/', to: 'lifetimes#update_single'
  # 	post '/lifetimes/:lifetime_id/comments', to: 'comments#create'
  # 	post '/lifetimes/:lifetime_id/like', to: 'likes#create'
  # 	delete '/lifetimes/:lifetime_id/like', to: 'likes#destroy'

  # 	delete '/comments/:id', to: 'comments#destroy'

  # 	post '/login', to: 'users#login'
  # 	post '/signup', to: 'users#signup'

  # 	get '/users/', to: 'users#index'
  # 	get '/users/:id/lifetimes', to: 'users#lifetimes'
  # 	get '/users/:id/', to: 'users#single'

  # 	post '/subscribe', to: 'subscriptions#create'
  # end

  get '/lifetimes/new', to: 'lifetimes#new', as: :new_lifetime
  get '/saved', to: 'savings#index', as: :saved_lifetimes

  resources :lifetimes, only: %i[create destroy] do # update logic is implemented below
    member do
      patch ':year', to: 'lifetimes#update_single'
      get '(:year)', to: 'lifetimes#single', as: :single
    end

    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    resources :savings, only: %i[create destroy]
  end

  resources :subscriptions, only: [:create]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'me', to: 'users/profiles#me', as: :my_profile
    get 'me/edit', to: 'users/profiles#edit', as: :edit_profile

    resources :followings, only: %i[create destroy]

    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/sessions#new_challenge', as: :new_user_session_challenge

    post 'reauthenticate/new_challenge', to: 'users/reauthentication#new_challenge', as: :new_user_reauthentication_challenge
    post 'reauthenticate', to: 'users/reauthentication#reauthenticate', as: :user_reauthentication

    namespace :users do
      resources :passkeys, only: %i[index create destroy] do
        collection do
          post :new_create_challenge
        end

        member do
          post :new_destroy_challenge
        end
      end

      get ':id', to: 'profiles#single', as: :single_profile, constraints: { id: /\d+/ }
      get ':username', to: 'profiles#single_by_username', as: :single_profile_by_username
      patch ':id', to: 'profiles#update_single', as: :update_single_profile
      get ':id/followers', to: 'profiles#followers', as: :user_followers
      get ':id/followings', to: 'profiles#followings', as: :user_followings
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include ApplicationHelper
  include ImageCompressible

  validates :username, uniqueness: true, format: { with: /\A[a-z0-9_]+\z/, message: 'can only contain lowercase letters, numbers, and underscores' }, length: { in: 3..10, message: 'must be between 3 and 10 characters' }, allow_nil: true

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_many :lifetimes, dependent: :destroy
  has_many :comments, dependent: :nullify
  has_many :likes, dependent: :destroy
  has_many :liked_lifetimes, through: :likes, source: :lifetime
  has_many :savings, dependent: :destroy
  has_many :saved_lifetimes, through: :savings, source: :lifetime
  has_many :active_followings, class_name: 'Following', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_followings, class_name: 'Following', foreign_key: 'followed_id', dependent: :destroy
  has_many :followings, through: :active_followings, source: :followed
  has_many :followers, through: :passive_followings, source: :follower
  has_many :passkeys, dependent: :destroy

  has_one_attached :profile_picture

  validates :profile_picture, content_type: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif'], size: { less_than: 1.megabytes }

  devise :passkey_authenticatable, :database_authenticatable, :registerable, :rememberable

  def following?(other_user)
    followings.include?(other_user)
  end

  def followings_count
    followings.count
  end

  def followers_count
    followers.count
  end

  def self.passkeys_class
    Passkey
  end

  def self.find_for_passkey(passkey)
    find_by(id: passkey.user.id)
  end
end

Devise.add_module :passkey_authenticatable,
    model: 'devise/passkeys/model',
    route: { session: [nil, :new, :create, :destroy] },
    controller: 'controller/sessions',
    strategy: true

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users/passkeys_controller.rb
# frozen_string_literal: true

module Users
  class PasskeysController < DeviseController
    include Devise::Passkeys::Controllers::PasskeysControllerConcern
    include RelyingParty

    # disable reauth
    def verify_reauthentication_token; end

    def user_details_for_registration
      { id: resource.webauthn_id || WebAuthn.generate_user_id, name: resource.email }
    end

    def set_relying_party_in_request_env
      request.env[relying_party_key] = relying_party
    end
  end
end

app/controllers/users/profiles_controller.rb
module Users
  class ProfilesController < ApplicationController
    include ApplicationHelper

    before_action :authenticate_user!, except: %i[single single_by_username]

    def me
      @user = current_user

      set_lifetimes

      render :single
    end

    def single
      @user = User.find(params[:id])

      set_lifetimes

      # If user has a username, redirect to username-based route
      return unless @user.username.present?

      redirect_to users_single_profile_by_username_path(@user.username)
      nil
    end

    def single_by_username
      @user = User.find_by!(username: params[:username])

      set_lifetimes

      render :single
    end

    def followers
      @user = User.find(params[:id])
      @followers = @user.followers

      render :followers
    end

    def followings
      @user = User.find(params[:id])
      @followings = @user.followings

      render :followings
    end

    def edit
      @user = current_user

      @delete_picture = params['delete-picture']

      @user.profile_picture.purge if @delete_picture
    end

    def update_single
      @user = current_user

      if @user.update(profile_params)
        flash[:notice] = 'Updated your data'
      else
        flash[:alert] = extract_errors(@user)
      end

      redirect_to action: :edit
    end

    private

    def profile_params
      params.require(:user).permit(:first_name, :last_name, :username, :profile_picture)
    end

    def set_lifetimes
      @lifetimes =
        if current_user && @user == current_user
          @user.lifetimes
        elsif current_user&.followings&.include?(@user) && @user.followings.include?(current_user)
          @user.lifetimes.where(visibility: :everyone).or(@user.lifetimes.where(visibility: :mutuals_only))
        else
          @user.lifetimes.where(visibility: :everyone)
        end
    end
  end
end

app/controllers/users/reauthentication_controller.rb
# frozen_string_literal: true

module Users
  class ReauthenticationController < DeviseController
    include Devise::Passkeys::Controllers::ReauthenticationControllerConcern
    include RelyingParty

    def set_relying_party_in_request_env
      request.env[relying_party_key] = relying_party
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    include ApplicationHelper
    include Devise::Passkeys::Controllers::RegistrationsControllerConcern
    include RelyingParty

    REGISTRATIONS_DISABLED = false

    def new
      if REGISTRATIONS_DISABLED
        flash[:notice] = 'New user registrations are temporarily disabled.'
        redirect_to root_path
      else
        super do
          @passkey_mode = params[:passkey] == '1'
          @hide_footer = true
        end
      end
    end

    def create
      if REGISTRATIONS_DISABLED
        flash[:notice] = 'New user registrations are temporarily disabled.'
        redirect_to root_path
      else
        build_resource(sign_up_params)

        resource.save

        if resource.persisted?
          create_passkey_for_resource(resource:)
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          flash[:error] = extract_errors(resource)

          redirect_to action: :new
        end
      end
    end

    def after_update_path_for(_resource)
      edit_user_registration_path
    end

    # disable reauth
    def verify_reauthentication_token; end

    # disable fields validation
    def require_email_and_passkey_label; end

    def passkey_create?
      params&.dig(:action) == 'create' && params&.dig(resource_name, :passkey_credential).present?
    end

    def create_passkey(resource:)
      return unless passkey_create?

      resource.passkeys.create!(
        label: passkey_params[:passkey_label],
        public_key: @webauthn_credential.public_key,
        external_id: Base64.strict_encode64(@webauthn_credential.raw_id),
        sign_count: @webauthn_credential.sign_count,
        last_used_at: Time.now.utc
      )
    end

    def verify_passkey_registration_challenge
      return unless passkey_create?

      @webauthn_credential = verify_registration(relying_party:)
    rescue ::WebAuthn::Error => e
      error_key = Warden::WebAuthn::ErrorKeyFinder.webauthn_error_key(exception: e)
      render json: { message: find_message(error_key) }, status: :bad_request
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    include Devise::Passkeys::Controllers::SessionsControllerConcern
    include RelyingParty

    def set_relying_party_in_request_env
      request.env[relying_party_key] = relying_party
    end

    def new
      super do
        @hide_footer = true
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def some_user_name(user)
    if !user.first_name.blank? && !user.last_name.blank?
      "#{user.first_name} #{user.last_name}"
    elsif !user.first_name.blank?
      user.first_name
    elsif !user.last_name.blank?
      user.last_name
    elsif !user.username.blank?
      user.username
    elsif !user.email.blank?
      user.email
    end
  end

  def some_user_profile_picture(user, thumbnail: false)
    if user.profile_picture.attached?
      if thumbnail
        image_tag user.thumbnail_image(:profile_picture)
      else
        image_tag user.compressed_image(:profile_picture)
      end
    else
      image 'profile_mock.webp'
    end
  end
end

app/views/users/profiles/_profile_heading.html.haml
- bottom_hidden ||= false

= render layout: 'shared/lapse', locals: { html_class: 'profile-heading' } do
    %div.content
        = some_user_profile_picture(@user)
        %div.content
            %h1.text-m.stroke.white= some_user_name(@user)
            %div.shared-bullet-list
                %p.text-xs.white
                    = link_to t('users.profiles.common.followers', count: @user.followers_count), users_user_followers_path(@user), class: 'white'
                    %span.bullet •
                    = link_to t('users.profiles.common.followings', count: @user.followings_count), users_user_followings_path(@user), class: 'white'
            - if current_user == @user
                = shared 'button', { size: 'xs', color: 'white', hollow: true, text: main_text, link: main_link, top: true, html_class: 'main-action' }
                - unless bottom_hidden
                    = shared 'button', { size: 'xs', color: 'white', textonly: true, text: t('users.profiles.common.logout'), method: :delete, link: destroy_session_path(@user), top: true }
            - elsif current_user
                - if current_user.following?(@user)
                    = shared 'button', { method: :delete, no_confirm: true, size: 'xs', color: 'white', hollow: true, text: t('users.profiles.common.unfollow'), link: following_url(@user.id), html_class: 'main-action' }
                - else
                    = shared 'button', { method: :post, no_confirm: true, size: 'xs', color: 'white', hollow: true, text: t('users.profiles.common.follow'), link: followings_url(id: @user.id), html_class: 'main-action' }
    %div.fill

app/views/users/profiles/_profile_settings_heading.html.haml
%p.text-l.stroke= t('users.profiles.settings.heading')
= shared 'tab_select', { items: [{ label: t('users.profiles.settings.basic_tab'), link: edit_profile_path }, { label: t('users.profiles.settings.security_tab'), link: edit_user_registration_path }, { label: t('users.profiles.settings.passkeys_tab'), link: users_passkeys_path }] }

app/views/users/profiles/edit.html.haml
%turbo-frame.profiles-single.profiles-edit.container{id: qualify(@user)}
  = notification
  %div.info-block
    = render partial: 'users/profiles/profile_heading', locals: { main_text: t('users.profiles.common.back_to_profile'), main_link: my_profile_path }

  %div.settings-block
    = render partial: 'users/profiles/profile_settings_heading'
    = form_for @user, url: users_single_profile_url(@user.id) do |f|
      = f.label :first_name, t('users.profiles.edit.first_name_label')
      = shared 'input', { html_class: 'blue', placeholder: t('users.profiles.edit.first_name_placeholder'), form_field: :first_name, form: f, value: @user.first_name }
      = f.label :last_name, t('users.profiles.edit.last_name_label')
      = shared 'input', { html_class: 'blue', placeholder: t('users.profiles.edit.last_name_placeholder'), form_field: :last_name, form: f, value: @user.last_name }
      = f.label :username, t('users.profiles.edit.username_label')
      = shared 'input', { html_class: 'blue', placeholder: t('users.profiles.edit.username_placeholder'), form_field: :username, form: f, value: @user.username }
      = f.label :profile_picture, t('users.profiles.edit.profile_picture_label')
      = shared 'file_button', { label: :profile_picture, fields: f, selected: @user.profile_picture.attached?, delete_param: 'delete-picture', id: @user.id, html_class: 'file-button' }
      = shared 'button', { text: t('users.profiles.edit.save_changes'), form: f, advance: true, size: 's', html_class: 'save-button' }

app/views/users/profiles/followers.html.haml
%turbo-frame.profiles-followers.container{id: qualify(@user)}
  = notification
  %div.info-block
    = render partial: 'users/profiles/profile_heading', locals: { main_text: t('users.profiles.common.back'), main_link: users_single_profile_path(@user) }

  %div
    %h1.text-l.stroke.heading= t('users.profiles.followers.heading')
    %div.followers-block
      - if @followers.empty?
        %p.text-s.stroke= t('users.profiles.followers.empty_state')
      - else
        - @followers.each do |follower|
          = shared 'profile_preview', { profile: follower }

app/views/users/profiles/followings.html.haml
%turbo-frame.profiles-followers.container{id: qualify(@user)}
  = notification
  %div.info-block
    = render partial: 'users/profiles/profile_heading', locals: { main_text: t('users.profiles.common.back'), main_link: users_single_profile_path(@user) }

  %div
    %h1.text-l.stroke.heading= t('users.profiles.followings.heading')
    %div.followers-block
      - if @followings.empty?
        %p.text-s.stroke= t('users.profiles.followings.empty_state')
      - else
        - @followings.each do |following|
          = shared 'profile_preview', { profile: following }

app/views/users/profiles/single.haml
.container.profiles-single
	%div
		%h2 профиль
		= link_to 'Настройки входа', '/users/edit'

		- @lifetimes.each do |lifetime|
			= link_to lifetime.title, single_lifetime_url(id: lifetime.id)

		= render "users/shared/links", resource_name: :user, devise_mapping: Devise.mappings[:user]

app/views/users/profiles/single.html.haml
%turbo-frame.profiles-single.container{id: qualify(@user)}
  = notification
  %div.info-block
    = render partial: 'users/profiles/profile_heading', locals: { main_text: t('users.profiles.common.settings'), main_link: edit_profile_path }

  %div.lifetimes-block
    %h1.text-l.stroke.heading= t('users.profiles.single.heading')
    %div.shared-lifetime-card-container
      - @lifetimes.each do |lifetime|
        = shared 'lifetime_card', { hide_profile_preview: true, lifetime: }