config/routes.rb
Rails.application.routes.draw do
  root 'common_pages#index'

  get '/locale/:locale', to: 'service#locale', as: :set_locale

  namespace :admin do
    resources :lifetimes
    resources :passkeys
    resources :periods
    resources :subscriptions
    resources :users

    root to: 'users#index'
  end

  # namespace :api do
  # 	get '/lifetimes/', to: 'lifetimes#index'
  # 	get '/lifetimes/:id/', to: 'lifetimes#single'
  # 	patch '/lifetimes/:id/', to: 'lifetimes#update_single'
  # 	post '/lifetimes/:lifetime_id/comments', to: 'comments#create'
  # 	post '/lifetimes/:lifetime_id/like', to: 'likes#create'
  # 	delete '/lifetimes/:lifetime_id/like', to: 'likes#destroy'

  # 	delete '/comments/:id', to: 'comments#destroy'

  # 	post '/login', to: 'users#login'
  # 	post '/signup', to: 'users#signup'

  # 	get '/users/', to: 'users#index'
  # 	get '/users/:id/lifetimes', to: 'users#lifetimes'
  # 	get '/users/:id/', to: 'users#single'

  # 	post '/subscribe', to: 'subscriptions#create'
  # end

  get '/lifetimes/new', to: 'lifetimes#new', as: :new_lifetime
  get '/saved', to: 'savings#index', as: :saved_lifetimes

  resources :lifetimes, only: %i[create destroy] do # update logic is implemented below
    member do
      patch ':year', to: 'lifetimes#update_single'
      get '(:year)', to: 'lifetimes#single', as: :single
    end

    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    resources :savings, only: %i[create destroy]
  end

  resources :subscriptions, only: [:create]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'me', to: 'users/profiles#me', as: :my_profile
    get 'me/edit', to: 'users/profiles#edit', as: :edit_profile

    resources :followings, only: %i[create destroy]

    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/sessions#new_challenge', as: :new_user_session_challenge

    post 'reauthenticate/new_challenge', to: 'users/reauthentication#new_challenge', as: :new_user_reauthentication_challenge
    post 'reauthenticate', to: 'users/reauthentication#reauthenticate', as: :user_reauthentication

    namespace :users do
      resources :passkeys, only: %i[index create destroy] do
        collection do
          post :new_create_challenge
        end

        member do
          post :new_destroy_challenge
        end
      end

      get ':id', to: 'profiles#single', as: :single_profile, constraints: { id: /\d+/ }
      get ':username', to: 'profiles#single_by_username', as: :single_profile_by_username
      patch ':id', to: 'profiles#update_single', as: :update_single_profile
      get ':id/followers', to: 'profiles#followers', as: :user_followers
      get ':id/followings', to: 'profiles#followings', as: :user_followings
    end
  end
end

app/controllers/common_pages_controller.rb
class CommonPagesController < ApplicationController
  def index
    @page_nav_name = 'home'

    @top_lifetimes = Lifetime.where(visibility: :everyone).order(view_count: :desc).limit(10)

    @top_users = User.joins(:passive_followings).group('users.id').order('COUNT(followings.id) DESC')
  end

  def promo
    @page_nav_name = 'promo'
  end

  def about
    @page_nav_name = 'about'
  end

  def search; end
end

app/helpers/common_pages_helper.rb
module CommonPagesHelper
end

app/views/common_pages/about.haml
.about-page.container
	= image_tag 'icon3.png', class: 'icon d'
	= image_tag 'icon3m.png', class: 'icon m'

app/views/common_pages/about.html.haml
.common-pages-about.container
	= image 'icon3.png', class: 'icon d'
	= image 'icon3m.png', class: 'icon m'

app/views/common_pages/index.haml
.about-page.container
	= image_tag 'icon5.png', class: 'icon d'

app/views/common_pages/index.html.haml
.common-pages-index.container
    = notification
    %div.lapse-block
        = render layout: 'shared/lapse' do
            %div.a
            %div.b
            %div.c
            %div.content
                %h1.text-xl.text-accent= t('common_pages.index.lapse_block.title')
                %p.text-m.stroke= t('common_pages.index.lapse_block.subtitle')
                = shared 'button', { size: 'xs', color: 'lightblue', text: t('common_pages.index.lapse_block.button'), link: new_lifetime_path }

    - unless @top_lifetimes.empty?
        %div.popular-block
            %h1.text-l.stroke.heading= t('.popular_block.heading')
            %div.shared-lifetime-card-container
                - @top_lifetimes.each do |i|
                    = shared 'lifetime_card', { lifetime: i }
            = shared 'footnote', { text: t('.popular_block.footnote'), link: '' }

    %div.about-block
        %div.content
            %h1.text-l.stroke.heading= t('.about_block.heading')
            %p.text-m= t('.about_block.description1')
            %p.text-m= t('.about_block.description2')
            %div.buttons
                = shared 'button', { size: 'xs', color: 'lightblue', text: t('.about_block.create_button'), link: new_lifetime_path }
                = shared 'button', { size: 'xs', color: 'lightblue', hollow: true, text: t('.about_block.login_button'), link: my_profile_path }
        %div.graphics
            = image 'lapse_year.svg'

app/views/common_pages/promo.haml
.container
	.promo-page
		= image_tag 'icon1.png', class: 'icon' 
		= render partial: 'shared/subscription'

app/views/common_pages/promo.html.haml
.container
	%div
		= image 'icon1.png', class: 'icon' 
		= shared 'subscription'

app/views/common_pages/search.haml
.container
	.search-page
		%h1 search page

app/views/common_pages/search.html.haml
.container
	%div
		%h1 search page