config/routes.rb
Rails.application.routes.draw do
  root 'common_pages#index'

  get '/locale/:locale', to: 'service#locale', as: :set_locale

  namespace :admin do
    resources :lifetimes
    resources :passkeys
    resources :periods
    resources :subscriptions
    resources :users

    root to: 'users#index'
  end

  # namespace :api do
  # 	get '/lifetimes/', to: 'lifetimes#index'
  # 	get '/lifetimes/:id/', to: 'lifetimes#single'
  # 	patch '/lifetimes/:id/', to: 'lifetimes#update_single'
  # 	post '/lifetimes/:lifetime_id/comments', to: 'comments#create'
  # 	post '/lifetimes/:lifetime_id/like', to: 'likes#create'
  # 	delete '/lifetimes/:lifetime_id/like', to: 'likes#destroy'

  # 	delete '/comments/:id', to: 'comments#destroy'

  # 	post '/login', to: 'users#login'
  # 	post '/signup', to: 'users#signup'

  # 	get '/users/', to: 'users#index'
  # 	get '/users/:id/lifetimes', to: 'users#lifetimes'
  # 	get '/users/:id/', to: 'users#single'

  # 	post '/subscribe', to: 'subscriptions#create'
  # end

  get '/lifetimes/new', to: 'lifetimes#new', as: :new_lifetime
  get '/saved', to: 'savings#index', as: :saved_lifetimes

  resources :lifetimes, only: %i[create destroy] do # update logic is implemented below
    member do
      patch ':year', to: 'lifetimes#update_single'
      get '(:year)', to: 'lifetimes#single', as: :single
    end

    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    resources :savings, only: %i[create destroy]
  end

  resources :subscriptions, only: [:create]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'me', to: 'users/profiles#me', as: :my_profile
    get 'me/edit', to: 'users/profiles#edit', as: :edit_profile

    resources :followings, only: %i[create destroy]

    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/sessions#new_challenge', as: :new_user_session_challenge

    post 'reauthenticate/new_challenge', to: 'users/reauthentication#new_challenge', as: :new_user_reauthentication_challenge
    post 'reauthenticate', to: 'users/reauthentication#reauthenticate', as: :user_reauthentication

    namespace :users do
      resources :passkeys, only: %i[index create destroy] do
        collection do
          post :new_create_challenge
        end

        member do
          post :new_destroy_challenge
        end
      end

      get ':id', to: 'profiles#single', as: :single_profile, constraints: { id: /\d+/ }
      get ':username', to: 'profiles#single_by_username', as: :single_profile_by_username
      patch ':id', to: 'profiles#update_single', as: :update_single_profile
      get ':id/followers', to: 'profiles#followers', as: :user_followers
      get ':id/followings', to: 'profiles#followings', as: :user_followings
    end
  end
end

app/models/lifetime.rb
class Lifetime < ApplicationRecord
  include ImageCompressible

  belongs_to :user

  validates :title, presence: true

  enum visibility: {
    everyone: 0,
    author_only: 1,
    link_only: 2,
    mutuals_only: 3
  }

  has_many :periods, dependent: :destroy
  accepts_nested_attributes_for :periods, allow_destroy: true, reject_if: :all_blank

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :savings, dependent: :destroy

  def saved_by?(user)
    savings.exists?(user_id: user&.id)
  end

  def liked_by?(user)
    likes.exists?(user_id: user&.id)
  end

  def like_count
    likes.count
  end

  def all_photos
    photos = periods.includes(photos_attachments: :blob).flat_map(&:photos)
    compressed_collection(photos)
  end

  def increment_view_count!
    increment!(:view_count)
  end
end

app/controllers/admin/lifetimes_controller.rb
module Admin
  class LifetimesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/lifetimes_controller.rb
class LifetimesController < ApplicationController
  include ApplicationHelper
  include LifetimesHelper

  before_action :authenticate_user!, only: %i[new create destroy update_single]

  def featured
    @featured = Lifetime.where(visibility: :everyone)
  end

  def new
    @lifetime = Lifetime.new

    @hide_footer = true
  end

  def create
    @lifetime = Lifetime.new(lifetime_params)
    @lifetime.user = current_user

    if @lifetime.save
      redirect_to action: :single, id: @lifetime.id, 'view-mode': :list, edit: true
    else
      flash[:alert] = extract_errors(@lifetime)
      redirect_to action: :new
    end
  end

  def destroy
    @lifetime = Lifetime.find(params[:id])

    @owned = @lifetime.user == current_user

    raise ActiveRecord::RecordInvalid unless @owned

    @lifetime.destroy

    redirect_to my_profile_path
  end

  def single
    @lifetime = Lifetime.find(params[:id])

    unless can_view_lifetime?(@lifetime)
      flash[:alert] = "You don't have permission to view this lifetime"

      redirect_to root_path and return
    end

    @owned = @lifetime.user == current_user

    @lifetime.increment_view_count! if request.headers['HTTP_X_SEC_PURPOSE'] != 'prefetch' && !@owned

    @years = years_from_periods(@lifetime.periods)
    @editable = !params[:edit].nil? && @owned
    @view_mode = params['view-mode']&.to_sym || :donut
    @calendar =
      case params['cal']
      when 'c' # китайский
        %i[qingming guyu lixia xiaoman mangzhong xiazhi xiaoshu dashu liqiu chushu bailu qiufen hanlu shuangjiang lidong xiaoxue daxue dongzhi xiaohan dahan lichun yushui jingzhe chunfen]
      when 'j' # еврейский
        %i[nissan iyar sivan tammuz av elul tishrei cheshvan kislev tevet shvat adar]
      when 'p' # персидский
        %i[farvardin ordibehesht khordad tir mordad shahrivar mehr aban azar dey bahman esfand]
      when 'i' # индийский
        %i[vaisakha jyaistha asadha sravana bhadrapada asvina kartika agrahayana pausa magha phalguna chaitra]
      else # григорианский
        %i[april may june july august september october november december january february march]
      end

    delete_period_photo = params['delete-period-photo']
    year = params[:year].to_i

    @selected_year =
      if year && @years.include?(year)
        year
      elsif !@years.empty?
        @years.last
      else
        Time.now.year
      end

    index = @years.index(@selected_year) || 0

    @previous_year = index.positive? ? @years[index - 1] : nil
    @next_year = @years[index + 1]

    @periods =
      if @view_mode == :donut
        periods_of_year(@lifetime.periods, @selected_year)
      else
        @lifetime.periods
      end

    return unless delete_period_photo

    period = @lifetime.periods.find(delete_period_photo)

    raise ActiveRecord::RecordInvalid unless @owned

    period.photos.purge

    redirect_to set_param(['edit', 1], ['delete-period-photo', nil], current_params: request.query_parameters)
  end

  def update_single
    @lifetime = Lifetime.find(params[:id])
    @selected_year = params[:year] ? params[:year].to_i : Time.now.year

    raise ActiveRecord::RecordInvalid unless @lifetime.user == current_user

    view_mode = params[:lifetime][:view_mode].dup
    new_period = params['new-period']
    delete_period = params['delete-period']

    if @lifetime.update(lifetime_params)
      if new_period
        @lifetime.periods.create({ title: '', description: '', start: Date.new(@selected_year, 1, 1), end: Date.new(@selected_year, 1, 2) })

        redirect_to set_param(['edit', 1], current_params: request.query_parameters)
      elsif delete_period
        period = @lifetime.periods.find(delete_period)

        period.destroy

        redirect_to set_param(['edit', 1], current_params: request.query_parameters)
      else
        redirect_to action: :single, year: params[:year], 'view-mode': view_mode
      end
    else
      flash[:alert] = extract_errors(@lifetime)
      redirect_to action: :single, year: params[:year], 'view-mode': view_mode, 'edit': 1
    end
  end

  private

  def can_view_lifetime?(lifetime)
    case lifetime.visibility
    when 'everyone', 'link_only'
      true
    when 'author_only'
      lifetime.user == current_user
    when 'mutuals_only'
      if !current_user
        false
      elsif lifetime.user == current_user
        true
      else
        current_user.followings.include?(lifetime.user) && lifetime.user.followings.include?(current_user)
      end
    end
  end

  def permit_lifetime_params(params)
    if params[:lifetime][:periods_attributes].present?
      params[:lifetime][:periods_attributes].each_value do |period|
        period.delete(:photos) if period[:photos] == ['']
      end
    end

    params.require(:lifetime).permit(:title, :description, :start_point, :finish_point, :visibility, periods_attributes: [:id, :title, :description, :color_hex, :start, :end, { photos: [] }])
  end

  def lifetime_params
    permit_lifetime_params(params)
  end
end

app/helpers/lifetimes_helper.rb
module LifetimesHelper
  def friendly_date(date)
    date.strftime('%-d.%m.%Y')
  end

  def years_from_periods(periods)
    periods.map { |i| (i.start.year..i.end.year).to_a }.flatten.uniq.sort
  end

  def periods_of_year(periods, year)
    periods.select do |i|
      i.start.year <= year && i.end.year >= year
    end
  end

  def position_label(deg)
    {
      style: "margin-left: calc(var(--offset) * cos(#{deg}deg)); margin-top: calc(var(--offset) * sin(#{deg}deg))"
    }
  end

  def set_param(*params, current_params: nil)
    current_params ||= request.query_parameters.dup

    set = lambda do |key, value|
      if value
        current_params[key] = value
      else
        current_params.delete(key)
      end
    end

    if params[0].is_a? Array
      params.each { |param| set.call(param[0], param[1]) }
    else
      set.call(params[0], params[1])
    end

    "#{request.path}?#{current_params.to_query}"
  end
end

app/views/lifetimes/_comments.html.haml
%turbo-frame.comments{id: qualify(@lifetime, 'comments')}
    .existing
        - @lifetime.comments.each do |comment|
            %div.comment
                %p.text-s= comment.content
                = shared 'profile_preview', { profile: comment.user }
        
        - if current_user
            = form_with model: [@lifetime, @lifetime.comments.build] do |form|
                = form.text_area :content, class: 'text-s', placeholder: t('lifetimes.comments.leave_comment')
                = shared 'button', { text: t('lifetimes.comments.send'), color: 'lightblue', size: 'xs', hollow: true, form: }

app/views/lifetimes/_labels.html.haml
- months = @calendar.map do |month|
    - { short: t("date.month_names.#{month}.short"), full: t("date.month_names.#{month}.full") }

- with_bullets = months.length == 12

.labels
    - months.each_with_index do |month, index|
        - value = 360 / months.length * index
        - if with_bullets
            %p.text-s{**position_label(value + 15)} •
        %p.text-s{title: month[:full], **position_label(value)}= month[:short]

app/views/lifetimes/_likes.html.haml
%turbo-frame.likes{id: qualify(@lifetime, 'likes')}
    - if current_user
        - if @lifetime.liked_by?(current_user)
            = shared 'button', size: 'xs', color: 'lightblue', hollow: true, method: :delete, no_confirm: true, link: lifetime_like_url(@lifetime, @lifetime.likes.find_by(user: current_user)), text: t('lifetimes.likes.unlike')
        - else
            = shared 'button', size: 'xs', color: 'lightblue', hollow: true, method: :post, no_confirm: true, link: lifetime_likes_url(@lifetime), text: t('lifetimes.likes.like')
    %div.count
        %p.text-s.stroke.lightblue= @lifetime.like_count

app/views/lifetimes/_periods.haml
- last_year = nil

%div.periods
	%h2 периоды
	- @periods.each do |period|
		- if last_year != period.start.year
			%h3= period.start.year
			- last_year = period.start.year
		= render partial: 'shared/period', locals: { enabled: @editable, period:, form: }
	
	- if @editable
		= render partial: 'shared/button', locals: { text: 'Добавить', link: set_param('new', 1), size: 's', html_class: 'edit-button' }
		= @new_period

app/views/lifetimes/_periods.html.haml
- hide_years ||= false

- last_year = nil

.periods
	- @periods.each do |period|
		- if !hide_years && last_year != period.start.year
			%h3= period.start.year
			- last_year = period.start.year
		= shared 'period', { enabled: @editable, period:, form: }
	
	- if @editable
		= shared 'button', { text: t('lifetimes.periods.add_period'), form:, advance: true, form_submit_param: 'new-period', size: 's', html_class: 'edit-button' }

app/views/lifetimes/_save_button.html.haml
- if current_user && @lifetime.user != current_user
  %turbo-frame.save-button{id: qualify(@lifetime, 'saves')}
    - if @lifetime.saved_by?(current_user)
      = shared 'button', size: 'xs', color: 'lightblue', hollow: true, method: :delete, no_confirm: true, link: lifetime_saving_url(@lifetime, @lifetime.savings.find_by(user: current_user)), text: t('lifetimes.save_button.unsave')
    - else
      = shared 'button', size: 'xs', color: 'lightblue', hollow: true, method: :post, no_confirm: true, link: lifetime_savings_url(@lifetime), text: t('lifetimes.save_button.save')

app/views/lifetimes/_year_switcher.html.haml
.year-switcher
    %p.text-xl= @selected_year
    %div
        - if @previous_year
            = top_link_to '←', single_lifetime_url(id: @lifetime.id, year: @previous_year, cal: params['cal'], edit: params['edit'])
        - if @next_year
            = top_link_to '→', single_lifetime_url(id: @lifetime.id, year: @next_year, cal: params['cal'], edit: params['edit'])

app/views/lifetimes/featured.haml
.container
	.featured-lifetimes
		%h1 featured page

	- @featured.each do |feature|
		%p= feature.title

app/views/lifetimes/featured.html.haml
.lifetimes-featured.container
	%div
		%h1 featured page

		- @featured.each do |feature|
			%p= feature.title

app/views/lifetimes/new.haml
.container
	= form_for @lifetime, html: {class: 'single-lifetime'} do |form|
		- if alert
			%h2= alert
		= render partial: 'shared/editable_text', locals: { tag: 'h2', text: 'Название', enabled: true, form_field: :title, form: }
		= render partial: 'shared/editable_text', locals: { tag: 'p', text: 'Описание', enabled: true, form_field: :description, form: }

		= render partial: 'shared/button', locals: { text: 'Далее', form:, size: 'm', html_class: 'edit-button' }

app/views/lifetimes/new.html.haml
.lifetimes-new.container
	= notification
	= form_for @lifetime, data: { turbo_visit_control: 'reload' } do |form|
		= render layout: 'shared/lapse' do
			%div
				= shared 'icon', { name: 'plus', color: 'lightblue' }

		%div.info-block
			= shared 'editable_text', { html_class: 'text-l stroke', text: '', placeholder: t('lifetimes.new.title_placeholder'), enabled: true, form_field: :title, form: }
			= shared 'editable_text', { html_class: 'text-s description', text: '', placeholder: t('lifetimes.new.description_placeholder'), enabled: true, form_field: :description, form: }

			= shared 'points', { form: form }

			= shared 'button', { text: t('lifetimes.new.next_button'), form:, size: 'xs', html_class: 'edit-button' }

app/views/lifetimes/single.haml
.container
	= form_for @lifetime, url: single_lifetime_url(id: @lifetime.id, year: @selected_year), html: {class: 'single-lifetime'} do |form|
		= form.hidden_field :view_mode, value: @view_mode

		= render partial: 'shared/editable_text', locals: { tag: 'h2', text: @lifetime.title, enabled: @editable, form_field: :title, form: }
		= render partial: 'shared/editable_text', locals: { tag: 'p', text: @lifetime.description, enabled: @editable, form_field: :description, form: }

		= render partial: 'shared/tab_select', locals: { items: [{ label: 'По годам', link: set_param('view-mode', 'donut') }, { label: 'Списком', link: set_param('view-mode', 'list') }] }

		- if @view_mode == :donut
			%div.years
				- @years.each do |year|
					- if year == @selected_year
						%p= year
					- else
						= link_to year, single_lifetime_url(id: @lifetime.id, year: year)

		%div.info{class: @view_mode}
			- if @view_mode == :donut
				%div.description

				%div.chart{'data-controller': 'lifetime', 'data-action': 'periodChanged@document->lifetime#handlePeriodChanged', 'data-lifetime-periods': @periods.to_json, 'data-lifetime-selected-year': @selected_year}
					%div
						%canvas{'data-lifetime-target': 'canvas'}

			= render partial: 'lifetimes/periods', locals: { form: }

		- if @editable
			= render partial: 'shared/button', locals: { text: 'Сохранить', form:, size: 'm', html_class: 'edit-button' }
		- else
			= render partial: 'shared/button', locals: { text: 'Редактировать', link: set_param('edit', 1), size: 'm', html_class: 'edit-button' }

app/views/lifetimes/single.html.haml
%turbo-frame.lifetimes-single.container{id: qualify(@lifetime)}
	= notification
	= form_for @lifetime, url: single_lifetime_url(id: @lifetime.id, year: @selected_year) do |form|
		= form.hidden_field :view_mode, value: @view_mode

		%div.chart-block{class: @view_mode}
			= render layout: 'shared/lapse' do
				- if @view_mode == :donut
					%div.chart{'data-controller': 'lifetime', 'data-action': 'periodChanged@document->lifetime#handlePeriodChanged', 'data-lifetime-periods': @periods.to_json, 'data-lifetime-selected-year': @selected_year}
						%canvas{'data-lifetime-target': 'canvas'}
					= render partial: 'lifetimes/year_switcher'
					= render partial: 'lifetimes/labels'
				- if @view_mode == :list || @periods.empty?
					%div.loop

		%div.info-block{class: cn(@view_mode, @lifetime.periods.empty? ? 'empty' : nil)}
			%div.left
				%div.title
					= shared 'editable_text', { html_class: 'text-l stroke', text: @lifetime.title, placeholder: t('lifetimes.single.title_placeholder'), enabled: @editable, form_field: :title, form: }
					= shared 'visibility_icon'
				= shared 'editable_text', { html_class: 'text-s description', text: @lifetime.description, placeholder: t('lifetimes.single.description_placeholder'), enabled: @editable, form_field: :description, form: }
				- if @editable
					= shared 'points', { form: form, text_start_point: @lifetime.start_point, text_finish_point: @lifetime.finish_point, }
					%div.visibility-select
						%label.text-s= t('lifetimes.single.visibility_label')
						= ':'
						= form.select :visibility, options_for_select([[t('lifetimes.single.visibility_options.public'), 'everyone'], [t('lifetimes.single.visibility_options.private'), 'author_only'], [t('lifetimes.single.visibility_options.link_only'), 'link_only'], [t('lifetimes.single.visibility_options.mutuals_only'), 'mutuals_only']], @lifetime.visibility), {}, { class: 'form-select' }
				= shared 'tab_select', { selected_param_key: nil, items: [{ label: t('lifetimes.single.by_year_tab'), link: set_param('view-mode', 'donut'), key: 'donut' }, { label: t('lifetimes.single.list_tab'), link: set_param('view-mode', 'list'), key: 'list' }] }
				- if @view_mode == :donut
					= shared 'dropdown_select', { selected_param_key: 'cal', items: [{ label: t('lifetimes.single.calendar.gregorian'), link: set_param('cal', 'g'), key: 'g' }, { label: t('lifetimes.single.calendar.japanese'), link: set_param('cal', 'c'), key: 'c' }, { label: t('lifetimes.single.calendar.jewish'), link: set_param('cal', 'j'), key: 'j' }, { label: t('lifetimes.single.calendar.persian'), link: set_param('cal', 'p'), key: 'p' }, { label: t('lifetimes.single.calendar.indian'), link: set_param('cal', 'i'), key: 'i' }] }
				- if @editable
					= shared 'button', { text: t('lifetimes.single.save_changes'), form:, advance: true, size: 'xs' }
				- elsif @owned
					= shared 'button', { text: t('lifetimes.single.edit'), link: set_param('edit', 1), advance: true, size: 'xs' }
			%div.right
				- if @view_mode == :donut
					= render partial: 'lifetimes/periods', locals: { hide_years: true, form: }

		- if @view_mode == :list
			%div.periods-block
				= render partial: 'lifetimes/periods', locals: { form: }

	%div.social-block
		= shared 'profile_preview', { profile: @lifetime.user }
		%div.actions
			= render partial: 'lifetimes/save_button'
			= render partial: 'lifetimes/likes'

	- if @owned && @editable
		%div.actions-block
			= shared 'button', { text: t('lifetimes.single.delete'), link: single_lifetime_url, top: true, method: :delete, size: 'xs', color: 'red' }

	- unless @editable
		%div.comments-block
			%h1.text-l.stroke.heading= t('lifetimes.single.comments_heading')
			= render partial: 'lifetimes/comments'